### ISSUE TITLE
这里这样翻译可能读起来会更好点

### ISSUE THREAD

**Issue by LeoRoll** [linganmin/laradock-doc-zh#3]
https://laradock-docs.linganmin.cn/zh/documentation/#%E4%BD%BF%E7%94%A8phpmyadmin
![image](https://user-images.githubusercontent.com/21209623/45292707-8fc26080-b528-11e8-9cb3-bf07fff417c3.png)
https://laradock-docs.linganmin.cn/zh/documentation/#%E4%BD%BF%E7%94%A8phpmyadmin
![image](https://user-images.githubusercontent.com/21209623/45292769-c5674980-b528-11e8-9cf3-6eb45a5fea67.png)
“ To use with MariaDB ”在这里觉得翻译为“在搭配 MariaDB 使用的时候”可能更顺畅。

**Comment by linganmin** [comment]
以参考建议修改，谢谢
