### ISSUE TITLE
这里是“文件”，多打了一个“夹”字

### ISSUE THREAD

**Issue by LeoRoll** [linganmin/laradock-doc-zh#4]
https://laradock-docs.linganmin.cn/zh/getting-started/#%E5%AE%89%E8%A3%85
![image](https://user-images.githubusercontent.com/21209623/45344829-3ebd7580-b5d7-11e8-8626-9405ecc443b9.png)
![image](https://user-images.githubusercontent.com/21209623/45344870-54329f80-b5d7-11e8-9c86-e3c6b59126cb.png)

**Comment by linganmin** [comment]
已经修改，谢谢
