### ISSUE TITLE
准备生产环境 多写了句子，翻译不连贯

### ISSUE THREAD

**Issue by LeoRoll** [linganmin/laradock-doc-zh#6]
中文链接：
> https://laradock-docs.linganmin.cn/zh/documentation/#%E5%87%86%E5%A4%87%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83%E7%9A%84laradock
![image](https://user-images.githubusercontent.com/21209623/45611458-14196400-ba92-11e8-84e5-cc9751c856a1.png)

英文链接：
> http://laradock.io/documentation/#prepare-laradock-for-production
![image](https://user-images.githubusercontent.com/21209623/45611401-ecc29700-ba91-11e8-9e12-f1a89ac92c8d.png)
首先：中文文档多了小红方框里的语句。
然后，原文的 `forwarded `，即：突出，前进， 觉得在此处应该等同于 `exposed`，所以翻译为`暴露`更好；
再者就是：原文的 `publish `，即：发布，出版，发行，但是看其英文解释里有这样一句话：print (something) in a book or journal so as to make it generally known. 即类似“映射”的意思。所以觉得这里应该翻译为“映射”。
最后就是：重新调整翻译的语序，目前是按12345进行，但是按照13425翻可能更好，而且 `unless specifically told not to` 这一句应该是双重否定表肯定。重新翻译如下：
> 注意：数据库( MySQL/MariaDB/...) 端口不应该暴露在生产环境中，这是非常危险的，除非有特殊告知需要暴露端口，因为 Docker 容器会自动映射到宿主机的端口上。所以一般情况下一定要删除这些行：

**Comment by linganmin** [comment]
@LeoRoll 小哥哥敢不敢自己改下提个pr，我最近工作太忙了，暂时来不及修呢

**Comment by LeoRoll** [comment]
ok
