### ISSUE TITLE
docker-compose启动NGINX报错

### ISSUE THREAD

**Issue by MrLegeek** [linganmin/laradock-doc-zh#8]
错误如下  [emerg] 6#6: getpwnam("www-data") failed in /etc/nginx/nginx.conf:1

要怎么修改nginx 用户啊  我改nginx.conf文件 改成其他的用户 还是报错

**Comment by MrLegeek** [comment]
？？

**Comment by linganmin** [comment]
问题还没解决？我看你之前自己关掉了，以为你解决了呢

**Comment by linganmin** [comment]
> ？？



> 问题还没解决？我看你之前自己关掉了，以为你解决了呢

111

**Comment by MrLegeek** [comment]
> > ？？
> 
> > 问题还没解决？我看你之前自己关掉了，以为你解决了呢
> 
> 111

没解决   用的是最新laradock   nginx/dockerfile 要怎么改？

**Comment by linganmin** [comment]
你怎么启动的，`Dockerfile`文件里有`adduser`的命令呀


`Dockerfile` 文件 最后一行
```bash
RUN apk update \
    && apk upgrade \
    && apk --update add logrotate \
    && apk add --no-cache openssl \
    && apk add --no-cache bash \
    && adduser -D -H -u 1000 -s /bin/bash www-data

````

**Comment by MrLegeek** [comment]
> 你怎么启动的，`Dockerfile`文件里有`adduser`的命令呀
> 
> ```shell
> RUN apk update \
>     && apk upgrade \
>     && apk --update add logrotate \
>     && apk add --no-cache openssl \
>     && apk add --no-cache bash \
>     && adduser -D -H -u 1000 -s /bin/bash www-data
> ```
 
最新的是：
RUN apk update \
    && apk upgrade \
    && apk --update add logrotate \
    && apk add --no-cache openssl \
    && apk add --no-cache bash

RUN set -x ; \
    addgroup -g 82 -S www-data ; \
    adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1

**Comment by linganmin** [comment]
> > 你怎么启动的，`Dockerfile`文件里有`adduser`的命令呀
> > ```shell
> > RUN apk update \
> >     && apk upgrade \
> >     && apk --update add logrotate \
> >     && apk add --no-cache openssl \
> >     && apk add --no-cache bash \
> >     && adduser -D -H -u 1000 -s /bin/bash www-data
> > ```
> 
> 最新的是：
> RUN apk update 
> && apk upgrade 
> && apk --update add logrotate 
> && apk add --no-cache openssl 
> && apk add --no-cache bash
> 
> RUN set -x ; 
> addgroup -g 82 -S www-data ; 
> adduser -u 82 -D -S -G www-data www-data && exit 0 ; exit 1
> 
> 我直接用的是 docker-compose up -d nginx 启动的

我去拉个最新的试一下

**Comment by linganmin** [comment]
我用最新的也没有问题，你执行命令的目录是什么，最好能发个报错的截图，不然不好定位问题。提供个如下的图或者整个报错的信息：

```bash
☁  laradock [master] ⚡  dcupd nginx redis mysql
Starting laradock_mysql_1            ... done
Starting laradock_docker-in-docker_1 ... done
Starting laradock_redis_1            ... done
Starting laradock_workspace_1        ... done
Starting laradock_php-fpm_1          ... done
Starting laradock_nginx_1            ... done
```

**Comment by MrLegeek** [comment]
> 我用最新的也没有问题，你执行命令的目录是什么，最好能发个报错的截图，不然不好定位问题。提供个如下的图或者整个报错的信息：
> 
> ```shell
> ☁  laradock [master] ⚡  dcupd nginx redis mysql
> Starting laradock_mysql_1            ... done
> Starting laradock_docker-in-docker_1 ... done
> Starting laradock_redis_1            ... done
> Starting laradock_workspace_1        ... done
> Starting laradock_php-fpm_1          ... done
> Starting laradock_nginx_1            ... done
>


 ```

➜  laradock git:(master) doceker-compose up -d nginx
zsh: command not found: doceker-compose
➜  laradock git:(master) docker-compose up -d nginx
Recreating laradock_docker-in-docker_1 ... done
Recreating laradock_workspace_1        ... done
Recreating laradock_php-fpm_1          ... done
Recreating laradock_nginx_1            ... done
➜  laradock git:(master) docker-compose ps
       Name               Command         State          Ports
---------------------------------------------------------------------
laradock_docker-     dockerd-             Up       2375/tcp
in-docker_1          entrypoint.sh
laradock_mysql_1     docker-              Exit 0
                     entrypoint.sh
                     mysqld
laradock_nginx_1     /bin/bash            Exit 1
                     /opt/startup.sh
laradock_php-fpm_1   docker-php-          Up       9000/tcp
                     entrypoint php-fpm
laradock_phpmyadmi   /docker-             Exit 0
n_1                  entrypoint.sh apac
                     ...
laradock_redis_1     docker-              Exit 0
                     entrypoint.sh
                     redis ...
laradock_workspace   /sbin/my_init        Up       0.0.0.0:2222->22/t
_1                                                 cp
➜  laradock git:(master) cat logs/nginx/error.log
2019/07/06 03:04:28 [emerg] 10#10: getpwnam("www-data") failed in /etc/nginx/nginx.conf:1
2019/07/09 07:06:44 [emerg] 6#6: getpwnam("www-data") failed in /etc/nginx/nginx.conf:1
2019/07/09 07:07:14 [emerg] 6#6: getpwnam("www-data") failed in /etc/nginx/nginx.conf:1
2019/07/09 07:10:44 [emerg] 6#6: getpwnam("www-data") failed in /etc/nginx/nginx.conf:1
2019/07/09 09:11:08 [emerg] 7#7: getpwnam("www-data") failed in /etc/nginx/nginx.conf:1
➜  laradock git:(master)

``

**Comment by linganmin** [comment]
重新build一下

```bash
docker-compose build --no-cache nginx mysql 
```

**Comment by MrLegeek** [comment]
> 重新build一下试试
> 
> ```shell
> docker-compose build --no-cache nginx mysql 
> ```

突然好了  我之前build 好几次都是那个报错  这次build却好了  感谢🙏

**Comment by linganmin** [comment]
> > 重新build一下试试
> > ```shell
> > docker-compose build --no-cache nginx mysql 
> > ```
> 
> 突然好了 我之前build 好几次都是那个报错 这次build却好了 感谢🙏

之前你可能没加`--no-cache`

**Comment by MrLegeek** [comment]
> > > 重新build一下试试
> > > ```shell
> > > docker-compose build --no-cache nginx mysql 
> > > ```
> > 
> > 
> > 突然好了 我之前build 好几次都是那个报错 这次build却好了 感谢🙏
> 
> 之前你可能没加`--no-cache`

我加了  history |grep ....     都有的  真是神奇
